In [1]:
from utils.plot_utils import *
from utils.db_utils import *
from utils.orthanc_utils import *
import re
import pandas as pd

In [2]:
db = TinyDB(DB_PATH)

studies = fetch_db_studies()

# for study in studies[:4]:
study = studies[0]
# df = pd.DataFrame([series.__dict__ for series in study.series_dict.values()])

    # sax_df = df.loc[(df['series_type'] == 'Cine Stack') & (df['series_orientation'] == 'SAX')].sort_values('series_group').reset_index(drop= True)
    # sax_df = sax_df.loc[sax_df['dl_orthanc_id'].isna()]
    # series_group = sax_df['series_group'].value_counts().index[0]
    # sax_df = sax_df.loc[sax_df['series_group'] == series_group]
    # series_orthanc_ids = sax_df['orthanc_series_id'].values

In [3]:

df = pd.DataFrame([series.__dict__ for series in study.series_dict.values()])

sax_df = df.loc[(df['series_type'] == 'Cine Stack') & (df['series_orientation'] == 'SAX')].sort_values('series_group').reset_index(drop= True)
sax_df = sax_df.loc[sax_df['dl_orthanc_id'].isna()]
# series_group = sax_df['series_group'].value_counts().index[0]
# sax_df = sax_df.loc[sax_df['series_group'] == series_group]
# series_orthanc_ids = sax_df['orthanc_series_id'].values

In [4]:
df

,orthanc_series_id,series_uid,series_description,series_type,series_group,series_orientation,dl_orthanc_id,roundel_orthanc_id
0,01f66d80-effc83e0-b74b33b0-d3340ead-590d156f,1.3.12.2.1107.5.2.18.42363.2025083112093691090...,trufi_loc_multi_iPAT ECG__GT_ECG,Static Single,Axial_Static Single:00,Axial,None,None
1,026e2534-8553f200-a19eb909-fb21c4ed-184128d4,1.3.12.2.1107.5.2.18.42363.2025083112213687679...,T2Map_TrueFISP_MOCO_T2,Cine Single,nan_Cine Single:02,NaN,None,None
2,0336f01b-2bbec80b-38b70dec-5647d044-bd662ac9,1.3.12.2.1107.5.2.18.42363.2025083112290861564...,RT_cine 160res stack Physio Interp__GT_FIL_Phy...,Cine Single,nan_Cine Single:03,NaN,None,None
3,051eb357-12caf8b1-04bf29a4-e9f44ddc-42a419a6,1.3.12.2.1107.5.2.18.42363.2025083112263739157...,pre_MOLLI_5s(3s)3s_256_MOCO_T1,Cine Single,nan_Cine Single:04,NaN,None,None
4,07293d99-b11aca0f-c4f8daa7-9820d50f-fb90715d,1.3.12.2.1107.5.2.18.42363.2025083112212475944...,ML cine,Cine Stack,SAX_Cine Stack:00,SAX,f7a3c35c-692de856-0dc12c02-3665961b-7fe6de55,None
...,...,...,...,...,...,...,...,...
85,f9993ed2-7113b009-b569ed22-881ffd7e-0c4bc9a9,1.3.12.2.1107.5.2.18.42363.2025083112345579958...,flow_through plane,NaN,NaN,NaN,None,None
86,fa65a7b1-aca1ba6e-bf7bcbe4-4610735d-1ccdba4c,1.3.12.2.1107.5.2.18.42363.2025083112255888313...,pre_MOLLI_5s(3s)3s_256_MOCO_T1,Cine Single,nan_Cine Single:06,NaN,None,None
87,fccb1c0e-5bcc08b3-9ed7c0bf-d302e7f8-35e0fccb,1.3.12.2.1107.5.2.18.42363.2025083112232846367...,T2Map_TrueFISP_MOCO_T2,Cine Single,nan_Cine Single:09,NaN,None,None
88,fcd05ae2-96fa2b8f-e34fbb89-509e475d-8bbb96b9,1.3.12.2.1107.5.2.18.42363.2025083112213687442...,T2Map_TrueFISP_MOCO,Cine Single,nan_Cine Single:02,NaN,None,None
89,fec0e980-482da328-1d4171b0-f240dd3c-e4c03e02,1.3.12.2.1107.5.2.18.42363.2025083112290861397...,RT_cine 160res stack Physio Interp__GT_FIL_Phy...,Cine Single,nan_Cine Single:03,NaN,None,None

In [ ]:
df = pd.DataFrame([series.__dict__ for series in study.series_dict.values()])

In [ ]:
sax_df = df.loc[(df['series_type'] == 'Cine Stack') & (df['series_orientation'] == 'SAX')].sort_values('series_group').reset_index(drop= True)

np.False_

In [22]:
df = pd.DataFrame()

In [24]:
df.empty

True

In [150]:
df.loc[df['series_type'] == 'Cine Stack']

,orthanc_series_id,series_uid,series_description,series_type,series_group,series_orientation,dl_orthanc_id,roundel_orthanc_id
3,0ee29e7b-7acf4d7e-a23e39db-b6b25a7b-2c690438,1.2.276.0.7230010.3.1.3.0.82940.1733242372.590065,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,959bd907-9df11bfb-61d81ef6-12a4b337-a790d872,None
4,12083dab-116443d8-ff0f9f65-bd140c9f-23817157,1.2.276.0.7230010.3.1.3.0.82940.1733242375.591810,short_axis_cine stack,Cine Stack,SAX_Cine Stack:01,SAX,None,None
5,13ce63ff-40a95436-2ad9df73-b48339c9-ecf17ad3,1.2.276.0.7230010.3.1.3.0.82940.1733242372.590106,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,873d6c06-3b54b41d-b4193e14-ea54bb24-50f688fe,None
10,222fec5e-1eb1c6e1-4a824e77-74bef81d-5cce5818,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590352,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,c811c27a-0f4f8ee4-77bdb1f2-de9659b2-baf7e933,None
13,27e73d82-d9edc060-b74372ad-9f4e2a2b-b279c14d,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590311,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,95dad16f-38dc41fa-ea5b0093-d91fe47e-7978bb6a,None
14,28a16c30-02243afb-f83c2997-675b678d-2a4d3bef,1.2.276.0.7230010.3.1.3.0.82940.1733242372.589819,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,2507fc2c-873e5c0f-d5eda6a1-ba2b126f-4e62502b,None
16,2a2ea64d-3e0105a7-a513a4cc-0d14de01-e72a58f8,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590270,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,073b57d0-0d8b15d9-842c4392-190e5fcd-de1c0d3b,None
18,2a76fe17-ea02a438-e99abea2-2c523f73-c4b5b430,1.2.276.0.7230010.3.1.3.0.82940.1733242375.592015,short_axis_cine stack,Cine Stack,SAX_Cine Stack:01,SAX,None,None
25,4d6c3728-f6ab679b-2c1b5385-22402a56-94023315,1.2.276.0.7230010.3.1.3.0.82940.1733242372.589901,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,d86b448e-53d8a2d5-4600bf19-aff5871f-648e3467,None
32,612bb3f9-f6923415-51e72017-541fb871-2ba60e62,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590393,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,8bd84702-d0c57f53-065a5456-61f8a371-f53bc951,None
36,77e55252-3d2f9703-a167cf82-ac032613-c1a19f28,1.2.276.0.7230010.3.1.3.0.82940.1733242375.591933,short_axis_cine stack,Cine Stack,SAX_Cine Stack:01,SAX,None,None
37,7897f2cc-e4e179dc-37f85d3c-dd07c433-029844e3,1.2.276.0.7230010.3.1.3.0.82940.1733242372.589983,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,2c75cd95-731cab84-2f5b0121-a861abdc-d19c9ade,None
38,7f478170-9d15fb73-3666c41b-e55aca75-1d8a8b70,1.2.276.0.7230010.3.1.3.0.82940.1733242375.591851,short_axis_cine stack,Cine Stack,SAX_Cine Stack:01,SAX,None,None
44,902d90df-0c81909e-8f984c4d-60fe8eff-df6fd906,1.2.276.0.7230010.3.1.3.0.82940.1733242372.589942,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,b08b4d3f-7ace31ad-1649d1bc-e61464f1-4b08a744,None
48,9a3e0bef-5ada2b12-761120ca-cc1bc341-035a0bb6,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590188,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,695a3269-43008963-7841dff1-640566ef-4b10db8e,None
52,b26fef4e-7e0452ac-bdda2fea-1e3646fb-3a7c68cf,1.2.276.0.7230010.3.1.3.0.82940.1733242375.591892,short_axis_cine stack,Cine Stack,SAX_Cine Stack:01,SAX,None,None
55,be11160f-8e04dd7c-e45cfe09-8ff3092a-fd4dc827,1.2.276.0.7230010.3.1.3.0.82940.1733242375.591974,short_axis_cine stack,Cine Stack,SAX_Cine Stack:01,SAX,None,None
56,be4d89c4-e71939cd-ea0a637f-624bf3f2-196221bc,1.2.276.0.7230010.3.1.3.0.82940.1733242372.589860,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,6ea1461b-38bf423e-49e81102-e0cd6965-ee8a3c7a,None
58,c2d2b9eb-a6e59b71-65c204c1-69a1693f-210cdda9,1.2.276.0.7230010.3.1.3.0.82940.1733242372.590024,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,b6f227c3-15d426e5-5c1e310e-0c63c5f6-13846c3f,None
59,c74120cc-b8e0d5ff-7277d038-b80c53f0-c96bbb69,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590147,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,54611324-bb72f168-12ac5709-ba773575-2f0b5cd8,None
65,d77ae1f0-61b081f4-a6aa3283-25bf8981-2ed90f4a,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590229,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,fa95c926-c205df6f-51c6c3ca-a03cfff3-7226209a,None
68,e24455bc-2b6fce9c-7c54668b-e3b0214b-9bcd949b,1.2.276.0.7230010.3.1.3.0.82940.1733242373.590434,short_axis_cine stack,Cine Stack,SAX_Cine Stack:00,SAX,f0ef784b-734a19fd-c50973b3-967e2f74-87fd6cfe,None

In [126]:
for sid,series in study.series_dict.items():
    print(sid)

017c4324-8b4349c0-5f8698dd-d71527b5-66304ee6
03f9e3fb-adadeb87-ddb96ec5-2b0a9e51-c8c7a224
04591445-a4091023-19874f79-94b6e33f-1ce26f4c
05359c0c-fd5e1e62-f4799a13-0ee097e5-de442f95
0726b782-d035d87d-c90bb21c-adc4def7-9ab582b4
07618786-41b29ba5-74969b9e-0ecda847-2c4f2495
0817a808-21fd44a8-72c38420-08a2df93-9f3ab962
0870d370-24d65155-dbfb45c9-cddf209a-c196ecaf
0b15c697-dcf915a8-a4afe4e1-c4aa6b2d-8638afa0
0ce4c012-242315ad-ad505759-0813e844-25af8931
0d4de95f-1d118949-cf0e00fd-cae4e9fe-fb5b2e00
0e9f8816-09d09a54-249d8eab-7265790d-107148d9
0fc3cc19-f3e746cb-d1c100a7-2b1498f8-3e7b6e44
104a0004-f85a41cb-56a4d554-e9e5de59-66a9259a
11df27ef-4a440539-54f61b9d-3873a29f-e00ddfe0
1236eedc-48b5fe5c-6be24c92-376eaf74-a1ab883a
1519559a-f56f559b-6828aca7-31a9d092-96f06e40
1b9709f3-95e3d04f-17301a94-f595ec20-7f4d3bfb
1d0f6987-cdbd16dd-4ad53992-abf5816d-6e2cea30
1f1e1d34-51c9d99a-1ad33d97-574efc0a-64d0124b
204277cc-3706912a-0ea229e4-633ee84b-40a49327
21103ba1-9dcf426a-7286403b-a598ba47-14b9bc96
22b27f01-f7a10604-499cc2bd-44cc006d-aecb8507
29dd62fa-7e9963b8-e9c2268e-63cbc258-a4f2c65d
2a0bfb45-2f6d0f3f-f3abe566-48ba4e3e-f99dfa2a
31bba041-f2d471ec-cb145ae1-627bcd19-ca42a3f7
34e1ae8b-956742cc-007eda0b-1571b5fc-26b5af4d
3521255a-647ec458-53f10370-f7825d26-c5c44659
3ad005db-0a938504-f1770f8a-85966e3e-f7e9bfe7
3b56b8e2-7c1896cd-8cc6f07a-f7ca033b-78084b87
3c1a687c-46365b36-fa6559c5-281a862e-247dc90d
3db48026-9e0d1e3f-2cb756fc-2fb247f5-7bcf5019
3dce6594-e2c1a6a0-5739d296-96bdc00e-81039de9
3eaf728b-712fc39e-13aba035-b2886787-1ad04bd1
3efac551-34345ebe-92a65824-f2a81f53-1e49d84a
40435b6e-cf0b4169-58d036e4-4cd94077-5409bdfc
41721aee-d759497a-bdaa1948-7322764d-8c19a0eb
46bbad01-6e85f979-d392c544-31705973-98dce22b
4701831d-f320508a-0f5c3c6e-39ac7529-70e9d5a3
47239069-ebb7039e-bc218612-ba127e1b-6ad735e4
47385b37-7db15ab0-3312db2b-885e2d94-7ea40a1e
49202196-7073eb40-f96b2c69-56cc9dd1-e84fec58
4a3dfe1a-361b59e4-30db460f-21d12ba4-363c2337
4d8d5fa0-83077ee4-4b3e89b0-fe9677de-2b1a4b56
4d965eb9-dab73cc1-c1a6b6ad-0be7f4d3-d4089a26
4e501cc8-c56fcfb3-48113e28-6cca8423-190d3105
50341df6-d8c827f2-1b7fd6ca-efab7ba3-4a52f0fb
5261476b-187a2739-2dfdc2ce-106ac2f9-768e6c4d
52cacfd2-5922e049-6d03f87b-81eae65f-752a6c4c
567587a6-ebbcc1ab-4908979c-ee1aae0f-68a6bdfb
56ae74a5-30d807bd-444ed0df-3cb8a7fa-dca865bb
57be84d2-0e2c570d-3c1d1ed6-8346fe32-5c20633e
5a2953f6-f8b4fe1a-458883a2-e21cec2e-c9214feb
5a9e4c58-d7f91f21-3c0a9e29-74eb4c7b-32c3966d
5b0db4e9-e6e8b182-9c5d9bb9-e0df1877-75650efd
5c99023e-ec20c262-9a0c51d7-c6aabe85-78d407a8
5cc49c0e-367e9e62-cc2b580b-2d37d88e-2ed658b8
5d95e2bb-0a05a126-85e860d5-63457231-ea07f9dd
5f76438c-9e082466-bae705d6-4cb1b465-cc8a27ca
5fde3cd4-4b3c67ba-389e714d-5491a38c-36266e4c
60d6dc83-7f0df073-fcdecca2-0942d065-91c7326f
663317a0-0b68df4a-d218d93e-8c4dbc76-41a359fd
67174f86-170c0c4b-597c78b0-2cb2e0eb-1b5025e1
69518532-cdfbc5af-bd7fd5e9-44b1aaea-9f4fb173
6dcd1fc8-f08640b6-309269aa-58c0dcd3-539d6ebc
710d7088-ee22db64-bd9feebf-bc55af58-d30e75df
735a88b4-e3f8bc1a-55b3b893-230b645b-7e6425b9
739a027c-2ec11bfb-8e2547fd-0c76e96b-3f43a5a1
757b604a-d67b6032-626096aa-89c905d1-cad1016b
75b4763c-79b4fab2-bd4e6315-38e793d8-f1a34d01
7628c922-5aafbf0f-65f62a72-2fdde6ce-0894f0dc
7911330b-9e3adafe-2e5820a7-89baf3e7-d5c139e5
7a86be46-db9c6aca-46669c16-748b0cb9-b77f8d3e
7b7a4805-bd64d66c-9bdfaac7-2a127e1c-c50c765e
7da02d7e-29e4c9fc-5de5d29c-b9e0ef7a-c11102c2
7f5711d5-e302ed7f-e4e9d471-634dc2bf-f94d5748
7fca4bff-30f68426-4fa7aff9-4a8eaa4e-f5c31df6
8085190e-d274bdf7-215b25c6-f806c274-cb6dee34
81f47205-541dc5f0-10cff86e-52791fba-0874cb2b
8438f6dd-c4455c7e-35dab6cc-acca83d6-d1b8e61a
8922e7ae-2f8d9d9a-57300f7e-a9d2c800-45a0c9a5
8a61d4fe-0e89d273-5009e91d-5220774b-cbe8c4eb
8f770797-3bcff1fd-c3a6f384-32a8c31b-b1128e4e
910e8468-e070ceb1-9ee2700e-138d5dcc-91dfb2c0
93f4ac29-37a1e29c-5827e22c-db04e454-9b48f05c
95b90e75-f45cb13b-863eadd7-de9d24d7-1374e1c7
9650481b-054b37d9-86fb54b6-69bba724-f168404e
97ecf97c-5b9fed67-18c1185a-defa10b3-06383564
981824c4-0a2f23a6-36903735-74876aec-91f683c1
986efd64-743d39ca-35f2c3b1-64b33ba6-4a93b39a
990c09d0-d2efe9af-c4eb4d8c-35a964eb-eeaf71a5
9d445478-73e68bf5-6ab7a157-c64f2590-14149679
9ea970b7-8b2953ca-bc0d05d7-a5b20be0-e14a6fe3
9f70ead4-3cdb145e-acaeb1af-1b32845a-051c570d
a01250b7-5bcab83c-83d9beee-dd02b6b6-00b9c746
a42a27d9-728d8a12-b85091ec-4eb0403e-970d97cd
ab4c5852-1fa8ec67-d1143629-f02e26db-62e98244
ac2e3006-e210a0ea-e3606fb4-c58fac25-4d2fc1fb
ac6f7b8e-3f9fb53f-0465e344-3535f90f-22f4c08a
b03e5513-34bfdacd-96c78008-8a42a081-67ca676d
b05e3249-623a07c7-61121cb7-d3d342b8-8455561b
b08a1e9a-f0988f1e-19a15550-78908915-b76843dd
b08ecfc6-97670098-342870ae-8e8e8cc7-80725e18
b11d5f67-2bb8b783-8471bca3-fc6bb943-c174c6a8
b1cb17b6-ba4dd385-0112dac6-0c6d5226-0ccbec18
b2aee13d-1be933e0-1f5e8e3c-602f6182-9c2b9c1c
b54a4b74-eb5120ed-d780a92e-2951ba14-577a7082
b889001d-617125b3-3061cffa-aa1536f6-b3a2a302
b8ad0c4c-8ce97684-50a9c842-4b8711f7-a14d7c20
b8f84d10-6a1cdb97-c5647532-f49119ac-76fd77e4
c0d1058f-8e76098d-551c3384-8af7454b-7ec9db10
c2fcd2c3-df941837-548cfc8f-50356622-87ca066c
c5f6b9e0-36d6f6c8-a8835ad4-b52b3e29-ef47bc09
c7712ea2-02bfdb18-a74dc102-cca52c84-fe60cbcb
c7b65707-41627653-5f12d090-9a87e90a-9161fdec
c95d48a4-4e8144f9-2dd08a04-2d478b1f-498de44b
caa4f728-f746d78c-b526021b-7b41b24b-55f7c236
cd1ac265-35b020bc-eb851421-96fab0a8-e336945a
cfa49c22-cbcb2e55-18f1277e-534a9fca-185a86bb
cfb38f8e-1d101f68-e06068e4-2effcb5e-1ef053c9
d0e4a1e2-80c11b20-1c060227-18d4a0b9-36e20495
d119035b-42c4f79d-ef40d0db-346f0d9a-4ffd83a6
d238608f-eec7a1e5-3808abf3-e5bd55d6-ecd5a1a5
d38794bd-eef7e42d-b8a65aae-953234cb-4bafd590
d4fcc037-a3f3f621-66d19b7c-4778aab6-f23849cd
d516acf0-dfdb100f-db5a3c6a-8f6349b8-1faa44fc
d668cb2e-f793345a-3b63f8ed-b5c0e692-9ff62997
d6997b5a-b9b09b13-39140caa-4a9a1f04-0bfd7b80
d7a991a6-4497a868-9e0b0e83-7478dbf9-ae75fdc7
d92ced04-4f39a177-971bfde7-2a1f6134-bfc32f25
d9535591-6848c0e8-e9734b2b-1aac2316-08566dcc
d9bf8d5d-21e799a0-32aa8e0a-c1f8e3e9-4e924d4a
daa392b1-ca2d9c72-3e2e9fa9-4a2bb233-a15410ab
dae296be-7efc6a8f-a5adb408-46b19fcf-2f8e1e3c
db36895e-61e2f4ec-77fe7b05-4937e119-e0e71839
de0bda20-7136fb6a-84a198ce-ed44a3e6-8b979625
e0c3480a-1bb53492-b6f3cb89-46ae795b-67f03e1b
e1d822dd-27e99c9b-0cc038df-efa39f13-72629181
e278cb7a-bdac146c-65bbe230-1ef1e4bb-cd708cb4
e562c4b9-70d8db87-45c6c7d1-c8f331ab-cdd06421
e92d2cd6-1599fa88-6e876b3f-0439b7a9-68b5dadf
ec2bedb8-caf5408b-2bf0aafd-2d4edd5b-9ee5e9ab
ec850db6-ebabfe1d-c3f8da8c-54681402-cb130765
ed7abd07-1aaa9b5a-2f2002ac-359e2912-7316d95b
ee2061ae-62446340-30095439-320c7887-781a0b22
f136ce17-41f6b727-cafeae5f-5c1ea0ad-c4fdf186
f27214b9-6519e2e6-9f57854c-4db8a04b-1093b208
f2724165-e75289d4-28ed97dd-ce663a59-c8b73dda
f7775c05-81b39e3e-c34b77e6-2c5b0510-feeeb2fe
fbe48524-9b6fefe1-0d4121df-b808d461-324346d0
fc0326ab-100464ac-f9a89292-e0cf189c-61ca8d59
fc43057c-25b4919e-eb12a1f2-35ecdb6a-e559dac3
fd328461-18000c17-f410181f-9ecd9feb-f4bb7b9b
fddf7a7a-86d4ff95-5d34db68-7773fd0d-0ac66227

In [21]:
dicoms = fetch_orthanc_dicoms_for_series(new_df.iloc[-1]['orthanc_series_id'])
len(dicoms)

420

In [ ]:
# import requests
# import os
# try:
#     os.remove('image_clasp_db.json')
# except:
#     pass

# ORTHANC = "http://localhost:8042"
# AUTH = ("orthanc", "orthanc")

# session = requests.Session()
# session.auth = AUTH
# session.trust_env = False

# studies = session.get(f"{ORTHANC}/studies").json()

# for study_id in studies:
#     session.delete(f"{ORTHANC}/studies/{study_id}")