In [1]:
from utils.orthanc_utils import *
from utils.db_utils import *
from utils.plot_utils import *
from utils.pipeline import *


def get_volumes(dicoms):    
    df = pd.DataFrame(
        [{"SliceLocation": d.SliceLocation, "InstanceNumber": d.InstanceNumber, "PixelArray": d.pixel_array} for d in dicoms]
    ).sort_values(["SliceLocation", "InstanceNumber"])

    d0 = dicoms[0]
    pixel_spacing = float(d0.PixelSpacing[0])
    thickness = float(getattr(d0, "SpacingBetweenSlices", getattr(d0, "SliceThickness", np.nan)))
    voxel_size = (pixel_spacing ** 2 * thickness) / 1000
    
    array_4d = []
    for _, slice_df in df.groupby("SliceLocation"):
        time_array = []
        for _, time_df in slice_df.groupby("InstanceNumber"):
            pixel_array = time_df["PixelArray"].iloc[0]
            time_array.append(pixel_array)

        slice_array = np.stack(time_array, axis=-1)
        array_4d.append(slice_array)

    array_4d = np.stack(array_4d, axis=-2)

    labels = {500: "lv", 1000: "rv", 1500: "lv_myo", 2000: "rv_myo"}
    curves = {
        name: np.sum(array_4d == val, axis=(0, 1, 2)) * voxel_size
        for val, name in labels.items()
    }
    lv, rv = curves["lv"], curves["rv"]
    lv_edv, lv_esv = lv.max(), lv.min()
    rv_edv, rv_esv = rv.max(), rv.min()

    metrics = {
        "lv_edv": lv_edv,
        "lv_esv": lv_esv,
        "lv_ef": (lv_edv - lv_esv) / lv_edv,
        "lv_mass": np.mean(curves["lv_myo"]) * 1.05,
        "rv_edv": rv_edv,
        "rv_esv": rv_esv,
        "rv_ef": (rv_edv - rv_esv) / rv_edv,
        "rv_mass": np.mean(curves["rv_myo"]) * 1.05,
    }

    return metrics

2026-04-10 12:19:42.432 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
/home/tina/Documents/PhD/Project/imageCLASP/clasp/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-04-10 12:19:42.521 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-04-10 12:19:42.522 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2026-04-10 12:19:42.522 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [3]:
db = TinyDB(DB_PATH)
studies = fetch_db_studies()

study = studies[0]

'cc6fb873-9cbebf9c-322a7c90-85eadd68-56912070'

In [15]:
db = TinyDB(DB_PATH)
studies = fetch_db_studies()

study_dict = {}
for study in studies:
    df = pd.DataFrame([series.__dict__ for series in study.series_dict.values()])
    sax_dl_df = df[(df['dl_orthanc_id'].notna()) & (df['roundel_orthanc_id'].isna())]
    if len(sax_dl_df) > 0:
        study_dict[f'{study.patient_id} | {study.patient_name} | {study.study_date}'] = study

In [18]:
study

In [17]:
sax_dl_df

,orthanc_series_id,series_uid,series_description,series_type,series_group,series_orientation,dl_orthanc_id,roundel_orthanc_id
5,07618786-41b29ba5-74969b9e-0ecda847-2c4f2495,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,9d2aae58-63b5dbc4-683b7b3f-971e03ef-29f13703,None
7,0870d370-24d65155-dbfb45c9-cddf209a-c196ecaf,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,27567c90-947d46fb-8cbb6204-ca1bebd6-9d593c61,None
31,3db48026-9e0d1e3f-2cb756fc-2fb247f5-7bcf5019,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,4d1ae2ac-74af2a8a-67fc7a1b-813a3aae-60e01bd1,None
36,41721aee-d759497a-bdaa1948-7322764d-8c19a0eb,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,e7f5e1a8-b8e50c94-7b1c823e-44cfd6a2-ffcdacaa,None
58,5f76438c-9e082466-bae705d6-4cb1b465-cc8a27ca,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,e7b02609-c0047886-7699b978-9ea9a879-033e3415,None
65,710d7088-ee22db64-bd9feebf-bc55af58-d30e75df,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,d23bd8b4-cfec2299-041f8d8b-b6464ce4-84aa314b,None
69,75b4763c-79b4fab2-bd4e6315-38e793d8-f1a34d01,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,0430543a-3870d455-4ff3281d-593de98b-17d806be,None
84,93f4ac29-37a1e29c-5827e22c-db04e454-9b48f05c,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,e960e708-a0cb40d1-2fd351b9-8e3a2219-c39cc43f,None
87,97ecf97c-5b9fed67-18c1185a-defa10b3-06383564,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,e7a933ce-3ea89d37-d28a8d38-41e943bf-57344207,None
92,9ea970b7-8b2953ca-bc0d05d7-a5b20be0-e14a6fe3,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,f7523730-4e15087b-c9006230-d0db47db-9c1ec6e1,None
101,b08a1e9a-f0988f1e-19a15550-78908915-b76843dd,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,a1a2379e-9e17c84b-1bd03a38-798b4dcb-28dd2bca,None
107,b889001d-617125b3-3061cffa-aa1536f6-b3a2a302,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,179cf845-062d8fd7-490660c9-d752b045-7b1935d4,None
111,c2fcd2c3-df941837-548cfc8f-50356622-87ca066c,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,b80ad763-ddfee592-74d7b41a-7c6ed737-e4f3cd7c,None
138,e278cb7a-bdac146c-65bbe230-1ef1e4bb-cd708cb4,1.3.12.2.1107.5.2.18.42363.2025123109282085086...,SSFP,Cine Stack,Cine Stack:00,SAX,23e0ee8a-8cc0961c-152f978b-31d6baae-d701ab85,None

In [16]:
study.__dict__

{'series_dict': {'017c4324-8b4349c0-5f8698dd-d71527b5-66304ee6': <utils.db_utils.Series at 0x79cb48b79970>,
  '03f9e3fb-adadeb87-ddb96ec5-2b0a9e51-c8c7a224': <utils.db_utils.Series at 0x79cb48bbbec0>,
  '04591445-a4091023-19874f79-94b6e33f-1ce26f4c': <utils.db_utils.Series at 0x79cb48bbb620>,
  '05359c0c-fd5e1e62-f4799a13-0ee097e5-de442f95': <utils.db_utils.Series at 0x79cb48bb91c0>,
  '0726b782-d035d87d-c90bb21c-adc4def7-9ab582b4': <utils.db_utils.Series at 0x79cb48bbb080>,
  '07618786-41b29ba5-74969b9e-0ecda847-2c4f2495': <utils.db_utils.Series at 0x79cb48bbbe30>,
  '0817a808-21fd44a8-72c38420-08a2df93-9f3ab962': <utils.db_utils.Series at 0x79cb48bbb680>,
  '0870d370-24d65155-dbfb45c9-cddf209a-c196ecaf': <utils.db_utils.Series at 0x79cb48bbb830>,
  '0b15c697-dcf915a8-a4afe4e1-c4aa6b2d-8638afa0': <utils.db_utils.Series at 0x79cb48bbb020>,
  '0ce4c012-242315ad-ad505759-0813e844-25af8931': <utils.db_utils.Series at 0x79cb48bba900>,
  '0d4de95f-1d118949-cf0e00fd-cae4e9fe-fb5b2e00': <utils.db_utils.Series at 0x79cb48bbabd0>,
  '0e9f8816-09d09a54-249d8eab-7265790d-107148d9': <utils.db_utils.Series at 0x79cb48bb9100>,
  '0fc3cc19-f3e746cb-d1c100a7-2b1498f8-3e7b6e44': <utils.db_utils.Series at 0x79cb48bbb1a0>,
  '104a0004-f85a41cb-56a4d554-e9e5de59-66a9259a': <utils.db_utils.Series at 0x79cb48bbbcb0>,
  '11df27ef-4a440539-54f61b9d-3873a29f-e00ddfe0': <utils.db_utils.Series at 0x79cb48bb8740>,
  '1236eedc-48b5fe5c-6be24c92-376eaf74-a1ab883a': <utils.db_utils.Series at 0x79cb48bbb950>,
  '1519559a-f56f559b-6828aca7-31a9d092-96f06e40': <utils.db_utils.Series at 0x79cb48bbae10>,
  '1b9709f3-95e3d04f-17301a94-f595ec20-7f4d3bfb': <utils.db_utils.Series at 0x79cb48bbb440>,
  '1d0f6987-cdbd16dd-4ad53992-abf5816d-6e2cea30': <utils.db_utils.Series at 0x79cb48bbae70>,
  '1f1e1d34-51c9d99a-1ad33d97-574efc0a-64d0124b': <utils.db_utils.Series at 0x79cb48bbb5c0>,
  '204277cc-3706912a-0ea229e4-633ee84b-40a49327': <utils.db_utils.Series at 0x79cb48bbb800>,
  '21103ba1-9dcf426a-7286403b-a598ba47-14b9bc96': <utils.db_utils.Series at 0x79cb48bbb4a0>,
  '22b27f01-f7a10604-499cc2bd-44cc006d-aecb8507': <utils.db_utils.Series at 0x79cb48bbba70>,
  '29dd62fa-7e9963b8-e9c2268e-63cbc258-a4f2c65d': <utils.db_utils.Series at 0x79cb48bbb2c0>,
  '2a0bfb45-2f6d0f3f-f3abe566-48ba4e3e-f99dfa2a': <utils.db_utils.Series at 0x79cb48bbbe90>,
  '31bba041-f2d471ec-cb145ae1-627bcd19-ca42a3f7': <utils.db_utils.Series at 0x79cb48bb9370>,
  '34e1ae8b-956742cc-007eda0b-1571b5fc-26b5af4d': <utils.db_utils.Series at 0x79cb48bb8ec0>,
  '3521255a-647ec458-53f10370-f7825d26-c5c44659': <utils.db_utils.Series at 0x79cb48bbbaa0>,
  '3ad005db-0a938504-f1770f8a-85966e3e-f7e9bfe7': <utils.db_utils.Series at 0x79cb48bbb530>,
  '3b56b8e2-7c1896cd-8cc6f07a-f7ca033b-78084b87': <utils.db_utils.Series at 0x79cb48bbb650>,
  '3c1a687c-46365b36-fa6559c5-281a862e-247dc90d': <utils.db_utils.Series at 0x79cb48bbba10>,
  '3db48026-9e0d1e3f-2cb756fc-2fb247f5-7bcf5019': <utils.db_utils.Series at 0x79cb48bb9a60>,
  '3dce6594-e2c1a6a0-5739d296-96bdc00e-81039de9': <utils.db_utils.Series at 0x79cb48bbaff0>,
  '3eaf728b-712fc39e-13aba035-b2886787-1ad04bd1': <utils.db_utils.Series at 0x79cb48bbba40>,
  '3efac551-34345ebe-92a65824-f2a81f53-1e49d84a': <utils.db_utils.Series at 0x79cb48bba9f0>,
  '40435b6e-cf0b4169-58d036e4-4cd94077-5409bdfc': <utils.db_utils.Series at 0x79cb48bbb320>,
  '41721aee-d759497a-bdaa1948-7322764d-8c19a0eb': <utils.db_utils.Series at 0x79cb48bbbe00>,
  '46bbad01-6e85f979-d392c544-31705973-98dce22b': <utils.db_utils.Series at 0x79cb48bbb3e0>,
  '4701831d-f320508a-0f5c3c6e-39ac7529-70e9d5a3': <utils.db_utils.Series at 0x79cb48bba480>,
  '47239069-ebb7039e-bc218612-ba127e1b-6ad735e4': <utils.db_utils.Series at 0x79cb48bbbd40>,
  '47385b37-7db15ab0-3312db2b-885e2d94-7ea40a1e': <utils.db_utils.Series at 0x79cb48bbbbc0>,
  '49202196-7073eb40-f96b2c69-56cc9dd1-e84fec58': <utils.db_utils.Series at 0x79cb48bbb350>,
  '4a3dfe1a-361b59e4-30db460f-21d12ba4-363c2337': <utils.db_utils.Series at 0x79cb48bbb230>,
  '4d8d5fa0-83077ee4-4b3e89b0-fe9677de-2b1a4b56': <utils.db_utils.Series at 0x79cb48bba630>,
  '4d965eb9-dab73cc1-c1a6b6ad-0be7f4d3-d4089a26': <utils.db_utils.Series at 0x79cb48bb8f20>,
  '4e501cc8-c56fcfb3-48113e28-6cca8423-190d3105': <utils.db_utils.Series at 0x79cb48bb9040>,
  '50341df6-d8c827f2-1b7fd6ca-efab7ba3-4a52f0fb': <utils.db_utils.Series at 0x79cb48bba8d0>,
  '5261476b-187a2739-2dfdc2ce-106ac2f9-768e6c4d': <utils.db_utils.Series at 0x79cb48bbb740>,
  '52cacfd2-5922e049-6d03f87b-81eae65f-752a6c4c': <utils.db_utils.Series at 0x79cb48bbbf50>,
  '567587a6-ebbcc1ab-4908979c-ee1aae0f-68a6bdfb': <utils.db_utils.Series at 0x79cb48bba930>,
  '56ae74a5-30d807bd-444ed0df-3cb8a7fa-dca865bb': <utils.db_utils.Series at 0x79cb48bba810>,
  '57be84d2-0e2c570d-3c1d1ed6-8346fe32-5c20633e': <utils.db_utils.Series at 0x79cb48bb9a90>,
  '5a2953f6-f8b4fe1a-458883a2-e21cec2e-c9214feb': <utils.db_utils.Series at 0x79cb48bbbda0>,
  '5a9e4c58-d7f91f21-3c0a9e29-74eb4c7b-32c3966d': <utils.db_utils.Series at 0x79cb48bbbc80>,
  '5b0db4e9-e6e8b182-9c5d9bb9-e0df1877-75650efd': <utils.db_utils.Series at 0x79cb48bb90a0>,
  '5c99023e-ec20c262-9a0c51d7-c6aabe85-78d407a8': <utils.db_utils.Series at 0x79cb48bb9070>,
  '5cc49c0e-367e9e62-cc2b580b-2d37d88e-2ed658b8': <utils.db_utils.Series at 0x79cb48bbb380>,
  '5d95e2bb-0a05a126-85e860d5-63457231-ea07f9dd': <utils.db_utils.Series at 0x79cb48bbbc50>,
  '5f76438c-9e082466-bae705d6-4cb1b465-cc8a27ca': <utils.db_utils.Series at 0x79cb48bbaae0>,
  '5fde3cd4-4b3c67ba-389e714d-5491a38c-36266e4c': <utils.db_utils.Series at 0x79cb48bbadb0>,
  '60d6dc83-7f0df073-fcdecca2-0942d065-91c7326f': <utils.db_utils.Series at 0x79cb48bb8ef0>,
  '663317a0-0b68df4a-d218d93e-8c4dbc76-41a359fd': <utils.db_utils.Series at 0x79cb48bba6f0>,
  '67174f86-170c0c4b-597c78b0-2cb2e0eb-1b5025e1': <utils.db_utils.Series at 0x79cb48bbae40>,
  '69518532-cdfbc5af-bd7fd5e9-44b1aaea-9f4fb173': <utils.db_utils.Series at 0x79cb48bb9520>,
  '6dcd1fc8-f08640b6-309269aa-58c0dcd3-539d6ebc': <utils.db_utils.Series at 0x79cb48bb9d60>,
  '710d7088-ee22db64-bd9feebf-bc55af58-d30e75df': <utils.db_utils.Series at 0x79cb48bba7b0>,
  '735a88b4-e3f8bc1a-55b3b893-230b645b-7e6425b9': <utils.db_utils.Series at 0x79cb48bbade0>,
  '739a027c-2ec11bfb-8e2547fd-0c76e96b-3f43a5a1': <utils.db_utils.Series at 0x79cb48bbb200>,
  '757b604a-d67b6032-626096aa-89c905d1-cad1016b': <utils.db_utils.Series at 0x79cb48bbaf60>,
  '75b4763c-79b4fab2-bd4e6315-38e793d8-f1a34d01': <utils.db_utils.Series at 0x79cb48bba5d0>,
  '7628c922-5aafbf0f-65f62a72-2fdde6ce-0894f0dc': <utils.db_utils.Series at 0x79cb48bbac90>,
  '7911330b-9e3adafe-2e5820a7-89baf3e7-d5c139e5': <utils.db_utils.Series at 0x79cb48bbaed0>,
  '7a86be46-db9c6aca-46669c16-748b0cb9-b77f8d3e': <utils.db_utils.Series at 0x79cb48bb8ce0>,
  '7b7a4805-bd64d66c-9bdfaac7-2a127e1c-c50c765e': <utils.db_utils.Series at 0x79cb48bbb770>,
  '7da02d7e-29e4c9fc-5de5d29c-b9e0ef7a-c11102c2': <utils.db_utils.Series at 0x79cb48bbb4d0>,
  '7f5711d5-e302ed7f-e4e9d471-634dc2bf-f94d5748': <utils.db_utils.Series at 0x79cb48bb8d40>,
  '7fca4bff-30f68426-4fa7aff9-4a8eaa4e-f5c31df6': <utils.db_utils.Series at 0x79cb48bbab40>,
  '8085190e-d274bdf7-215b25c6-f806c274-cb6dee34': <utils.db_utils.Series at 0x79cb48bb9640>,
  '81f47205-541dc5f0-10cff86e-52791fba-0874cb2b': <utils.db_utils.Series at 0x79cb48bba9c0>,
  '8438f6dd-c4455c7e-35dab6cc-acca83d6-d1b8e61a': <utils.db_utils.Series at 0x79cb48bb9010>,
  '8922e7ae-2f8d9d9a-57300f7e-a9d2c800-45a0c9a5': <utils.db_utils.Series at 0x79cb48bbaf00>,
  '8a61d4fe-0e89d273-5009e91d-5220774b-cbe8c4eb': <utils.db_utils.Series at 0x79cb48bbad50>,
  '8f770797-3bcff1fd-c3a6f384-32a8c31b-b1128e4e': <utils.db_utils.Series at 0x79cb48bb8890>,
  '910e8468-e070ceb1-9ee2700e-138d5dcc-91dfb2c0': <utils.db_utils.Series at 0x79cb48bb9490>,
  '93f4ac29-37a1e29c-5827e22c-db04e454-9b48f05c': <utils.db_utils.Series at 0x79cb48bbbfb0>,
  '95b90e75-f45cb13b-863eadd7-de9d24d7-1374e1c7': <utils.db_utils.Series at 0x79cb48bb9ac0>,
  '9650481b-054b37d9-86fb54b6-69bba724-f168404e': <utils.db_utils.Series at 0x79cb48bba780>,
  '97ecf97c-5b9fed67-18c1185a-defa10b3-06383564': <utils.db_utils.Series at 0x79cb48bbb710>,
  '981824c4-0a2f23a6-36903735-74876aec-91f683c1': <utils.db_utils.Series at 0x79cb48bb9910>,
  '986efd64-743d39ca-35f2c3b1-64b33ba6-4a93b39a': <utils.db_utils.Series at 0x79cb48bbacc0>,
  '990c09d0-d2efe9af-c4eb4d8c-35a964eb-eeaf71a5': <utils.db_utils.Series at 0x79cb48bb8e90>,
  '9d445478-73e68bf5-6ab7a157-c64f2590-14149679': <utils.db_utils.Series at 0x79cb48bb8bc0>,
  '9ea970b7-8b2953ca-bc0d05d7-a5b20be0-e14a6fe3': <utils.db_utils.Series at 0x79cb48bbb290>,
  '9f70ead4-3cdb145e-acaeb1af-1b32845a-051c570d': <utils.db_utils.Series at 0x79cb48bbac60>,
  'a01250b7-5bcab83c-83d9beee-dd02b6b6-00b9c746': <utils.db_utils.Series at 0x79cb48bba240>,
  'a42a27d9-728d8a12-b85091ec-4eb0403e-970d97cd': <utils.db_utils.Series at 0x79cb48bba870>,
  'ab4c5852-1fa8ec67-d1143629-f02e26db-62e98244': <utils.db_utils.Series at 0x79cb48bb8e60>,
  'ac2e3006-e210a0ea-e3606fb4-c58fac25-4d2fc1fb': <utils.db_utils.Series at 0x79cb48bbad80>,
  'ac6f7b8e-3f9fb53f-0465e344-3535f90f-22f4c08a': <utils.db_utils.Series at 0x79cb48bb90d0>,
  'b03e5513-34bfdacd-96c78008-8a42a081-67ca676d': <utils.db_utils.Series at 0x79cb48bb9af0>,
  'b05e3249-623a07c7-61121cb7-d3d342b8-8455561b': <utils.db_utils.Series at 0x79cb48bbb0b0>,
  'b08a1e9a-f0988f1e-19a15550-78908915-b76843dd': <utils.db_utils.Series at 0x79cb48bbaab0>,
  'b08ecfc6-97670098-342870ae-8e8e8cc7-80725e18': <utils.db_utils.Series at 0x79cb48bbaf30>,
  'b11d5f67-2bb8b783-8471bca3-fc6bb943-c174c6a8': <utils.db_utils.Series at 0x79cb48bb8b90>,
  'b1cb17b6-ba4dd385-0112dac6-0c6d5226-0ccbec18': <utils.db_utils.Series at 0x79cb48bba8a0>,
  'b2aee13d-1be933e0-1f5e8e3c-602f6182-9c2b9c1c': <utils.db_utils.Series at 0x79cb48bba420>,
  'b54a4b74-eb5120ed-d780a92e-2951ba14-577a7082': <utils.db_utils.Series at 0x79cb48bb9790>,
  'b889001d-617125b3-3061cffa-aa1536f6-b3a2a302': <utils.db_utils.Series at 0x79cb48bb97c0>,
  'b8ad0c4c-8ce97684-50a9c842-4b8711f7-a14d7c20': <utils.db_utils.Series at 0x79cb48bba6c0>,
  'b8f84d10-6a1cdb97-c5647532-f49119ac-76fd77e4': <utils.db_utils.Series at 0x79cb48bbac30>,
  'c0d1058f-8e76098d-551c3384-8af7454b-7ec9db10': <utils.db_utils.Series at 0x79cb48bb9940>,
  'c2fcd2c3-df941837-548cfc8f-50356622-87ca066c': <utils.db_utils.Series at 0x79cb48bb8fe0>,
  'c5f6b9e0-36d6f6c8-a8835ad4-b52b3e29-ef47bc09': <utils.db_utils.Series at 0x79cb48bbaa50>,
  'c7712ea2-02bfdb18-a74dc102-cca52c84-fe60cbcb': <utils.db_utils.Series at 0x79cb48bba720>,
  'c7b65707-41627653-5f12d090-9a87e90a-9161fdec': <utils.db_utils.Series at 0x79cb48bbb890>,
  'c95d48a4-4e8144f9-2dd08a04-2d478b1f-498de44b': <utils.db_utils.Series at 0x79cb48bbbef0>,
  'caa4f728-f746d78c-b526021b-7b41b24b-55f7c236': <utils.db_utils.Series at 0x79cb48bb9dc0>,
  'cd1ac265-35b020bc-eb851421-96fab0a8-e336945a': <utils.db_utils.Series at 0x79cb48bba5a0>,
  'cfa49c22-cbcb2e55-18f1277e-534a9fca-185a86bb': <utils.db_utils.Series at 0x79cb48bb98b0>,
  'cfb38f8e-1d101f68-e06068e4-2effcb5e-1ef053c9': <utils.db_utils.Series at 0x79cb48bba990>,
  'd0e4a1e2-80c11b20-1c060227-18d4a0b9-36e20495': <utils.db_utils.Series at 0x79cb48bb9610>,
  'd119035b-42c4f79d-ef40d0db-346f0d9a-4ffd83a6': <utils.db_utils.Series at 0x79cb48bb9e50>,
  'd238608f-eec7a1e5-3808abf3-e5bd55d6-ecd5a1a5': <utils.db_utils.Series at 0x79cb48bbb8c0>,
  'd38794bd-eef7e42d-b8a65aae-953234cb-4bafd590': <utils.db_utils.Series at 0x79cb48bbaa20>,
  'd4fcc037-a3f3f621-66d19b7c-4778aab6-f23849cd': <utils.db_utils.Series at 0x79cb48bbbfe0>,
  'd516acf0-dfdb100f-db5a3c6a-8f6349b8-1faa44fc': <utils.db_utils.Series at 0x79cb48bbbb30>,
  'd668cb2e-f793345a-3b63f8ed-b5c0e692-9ff62997': <utils.db_utils.Series at 0x79cb48bbb1d0>,
  'd6997b5a-b9b09b13-39140caa-4a9a1f04-0bfd7b80': <utils.db_utils.Series at 0x79cb48bba840>,
  'd7a991a6-4497a868-9e0b0e83-7478dbf9-ae75fdc7': <utils.db_utils.Series at 0x79cb48bba600>,
  'd92ced04-4f39a177-971bfde7-2a1f6134-bfc32f25': <utils.db_utils.Series at 0x79cb48bb9c70>,
  'd9535591-6848c0e8-e9734b2b-1aac2316-08566dcc': <utils.db_utils.Series at 0x79cb48bba570>,
  'd9bf8d5d-21e799a0-32aa8e0a-c1f8e3e9-4e924d4a': <utils.db_utils.Series at 0x79cb48bb8f80>,
  'daa392b1-ca2d9c72-3e2e9fa9-4a2bb233-a15410ab': <utils.db_utils.Series at 0x79cb48bbbf20>,
  'dae296be-7efc6a8f-a5adb408-46b19fcf-2f8e1e3c': <utils.db_utils.Series at 0x79cb48bb9760>,
  'db36895e-61e2f4ec-77fe7b05-4937e119-e0e71839': <utils.db_utils.Series at 0x79cb48bbbad0>,
  'de0bda20-7136fb6a-84a198ce-ed44a3e6-8b979625': <utils.db_utils.Series at 0x79cb48720050>,
  'e0c3480a-1bb53492-b6f3cb89-46ae795b-67f03e1b': <utils.db_utils.Series at 0x79cb48720080>,
  'e1d822dd-27e99c9b-0cc038df-efa39f13-72629181': <utils.db_utils.Series at 0x79cb487200b0>,
  'e278cb7a-bdac146c-65bbe230-1ef1e4bb-cd708cb4': <utils.db_utils.Series at 0x79cb487200e0>,
  'e562c4b9-70d8db87-45c6c7d1-c8f331ab-cdd06421': <utils.db_utils.Series at 0x79cb48720110>,
  'e92d2cd6-1599fa88-6e876b3f-0439b7a9-68b5dadf': <utils.db_utils.Series at 0x79cb48720140>,
  'ec2bedb8-caf5408b-2bf0aafd-2d4edd5b-9ee5e9ab': <utils.db_utils.Series at 0x79cb48720170>,
  'ec850db6-ebabfe1d-c3f8da8c-54681402-cb130765': <utils.db_utils.Series at 0x79cb487201a0>,
  'ed7abd07-1aaa9b5a-2f2002ac-359e2912-7316d95b': <utils.db_utils.Series at 0x79cb487201d0>,
  'ee2061ae-62446340-30095439-320c7887-781a0b22': <utils.db_utils.Series at 0x79cb48720200>,
  'f136ce17-41f6b727-cafeae5f-5c1ea0ad-c4fdf186': <utils.db_utils.Series at 0x79cb48720230>,
  'f27214b9-6519e2e6-9f57854c-4db8a04b-1093b208': <utils.db_utils.Series at 0x79cb48720260>,
  'f2724165-e75289d4-28ed97dd-ce663a59-c8b73dda': <utils.db_utils.Series at 0x79cb48720290>,
  'f7775c05-81b39e3e-c34b77e6-2c5b0510-feeeb2fe': <utils.db_utils.Series at 0x79cb487202c0>,
  'fbe48524-9b6fefe1-0d4121df-b808d461-324346d0': <utils.db_utils.Series at 0x79cb487202f0>,
  'fc0326ab-100464ac-f9a89292-e0cf189c-61ca8d59': <utils.db_utils.Series at 0x79cb48720320>,
  'fc43057c-25b4919e-eb12a1f2-35ecdb6a-e559dac3': <utils.db_utils.Series at 0x79cb48720350>,
  'fd328461-18000c17-f410181f-9ecd9feb-f4bb7b9b': <utils.db_utils.Series at 0x79cb48720380>,
  'fddf7a7a-86d4ff95-5d34db68-7773fd0d-0ac66227': <utils.db_utils.Series at 0x79cb487203b0>},
 'orthanc_study_id': '627d8707-9ec50a40-12b3be39-12b6cb9f-33bcb2cd',
 'study_uid': '1.3.12.2.1107.5.2.18.42363.30000025123108510742300000004',
 'patient_name': 'Doe^Jack',
 'patient_id': '23456781',
 'patient_sex': 'F',
 'patient_dob': '19410101',
 'study_date': '20251231',
 'patient_age': 85}

In [10]:
study_list

{}

In [3]:
df = pd.DataFrame([series.__dict__ for series in study.series_dict.values()])
sax_dl_df = df[(df['dl_orthanc_id'].notna()) & (df['roundel_orthanc_id'].isna())]

for series_id, dl_series_id in zip(sax_dl_df["orthanc_series_id"], sax_dl_df["dl_orthanc_id"]):
    series = study.series_dict[series_id]
    image_dicoms = fetch_orthanc_dicoms_for_series(series_id)
    mask_dicoms = fetch_orthanc_dicoms_for_series(dl_series_id)

    masked_images = [image.pixel_array * (mask.pixel_array > 0) for image, mask in zip(image_dicoms, mask_dicoms) ]
    new_orthanc_id = send_series_to_orthanc(masked_images, image_dicoms, new_description='Roundel Processed')
    series.roundel_orthanc_id = new_orthanc_id

metrics = get_volumes(fetch_orthanc_dicoms_for_series_list(df["dl_orthanc_id"].dropna().unique()))
metrics['orthanc_study_id'] = study.orthanc_study_id
metrics['patient_id'] = study.patient_id
metrics['study_date'] = study.study_date

metrics_df = pd.read_csv(METRICS_PATH)
metrics_df = pd.concat([metrics_df, pd.DataFrame([metrics])]).set_index('orthanc_study_id')
metrics_df.to_csv(METRICS_PATH)

/tmp/ipykernel_203371/540095361.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  metrics_df = pd.concat([metrics_df, pd.DataFrame([metrics])]).set_index('orthanc_study_id')

In [4]:
metrics_df

,patient_id,study_date,lv_edv,lv_esv,lv_ef,lv_mass,rv_edv,rv_esv,rv_ef,rv_mass
orthanc_study_id,,,,,,,,,,
c84ff965-9b667fef-54070af3-b1386f1a-42841c76,67812345,20251201,30.866044,13.072321,0.576482,23.216613,58.395765,32.574646,0.442175,11.112382

In [2]:
import tk